---
- hosts: fortigate
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
   ansible_connection: httpapi
   ansible_python_interpreter: /usr/bin/python3
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  gather_facts: no
  tasks:
  - name: Add firewall policy
    fortios_firewall_policy:
      vdom:  "{{ vdom }}"
      access_token: "bd5gz348fznsywGf099Nqnkfj1f5wp"
      state: "present"
      firewall_policy:
        policyid: 10
        name: "TEST"
        action: "accept"
        srcintf:
          - name: "port2"
        dstintf:
          - name: "port3"
        srcaddr:
          - name: "R2 subnet"
        dstaddr:
          - name: "R1 subnet"
        service:
          - name: "PING"
        schedule: "always"
        nat: "enable"
