---
- name: "Instalar software"
  hosts: multipass
  gather_facts: false
  become: true

  tasks:
    - name: Instalar net-tools
      ansible.builtin.apt:
        name: "net-tools"
        state: present

    - name: Registrar info de red
      ansible.builtin.command:
        cmd: ifconfig
      register: info

    - name: Visualizar info de red
      ansible.builtin.debug:
        msg: "{{ info }}"