---
- name: Test ansible windows
  hosts: winservers
  gather_facts: false

  tasks:
    # - name: Prueba ping windows
    #   win_ping:

    # - name: Parar servicio audio
    #   ansible.windows.win_service:
    #     name: Audiosrv
    #     state: stopped

    # - name: Rearrancar
    #   ansible.windows.win_service:
    #     name: Audiosrv
    #     state: started

    - name: Descargar GIT
      ansible.windows.win_get_url:
        url: https://github.com/git-for-windows/git/releases/download/v2.40.0.windows.1/Git-2.40.0-64-bit.exe
        dest: C:\prueba\git.exe

    - name: Instalar GIT
      ansible.windows.win_package:
        path: C:\prueba\git.exe
        state: present
        arguments:
          - /VERYSILENT
          - /NORESTART
