---
- hosts: fortigate
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
   ansible_connection: httpapi
   ansible_python_interpreter: /usr/bin/python3
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  gather_facts: no
  tasks:
  - name: Gather interfaces info.
    fortios_monitor_fact:
      vdom:  "{{ vdom }}"
      access_token: "bd5gz348fznsywGf099Nqnkfj1f5wp"
      selector: 'system_interface'
    register: interfaces_info

  - name: Output the interface information.
    debug:
      var: interfaces_info
